/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddDepositModal: typeof import('./src/components/add-deposit-modal.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    JoinModal: typeof import('./src/components/JoinModal.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MyUnionMenu: typeof import('./src/components/my-union-menu.vue')['default']
    MyUnionModal: typeof import('./src/components/my-union-modal.vue')['default']
    MyUnionTabs: typeof import('./src/components/MyUnionTabs.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    RequestCreditModal: typeof import('./src/components/request-credit-modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    UnionMenu: typeof import('./src/components/union-menu.vue')['default']
  }
}
